M48
; DRILL file KiCad 10.0.1 date 2026-06-06T13:43:56
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-06T13:43:56-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X128.25Y-98.25
X171.0Y-123.5
X174.25Y-49.0
X217.25Y-74.25
T2
X151.152Y-57.892
M30
